apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stirling
  namespace: stirling
  labels:
    app.kubernetes.io/instance: stirling
    app.kubernetes.io/name: stirling
spec:
  rules:
    - host: changeme
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: stirling
                port:
                  name: http