apiVersion: v1
kind: Service
metadata:
  name: stirling
  namespace: stirling
  labels:
    app.kubernetes.io/instance: stirling
    app.kubernetes.io/name: stirling
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/instance: stirling
    app.kubernetes.io/name: stirling
  type: ClusterIP