apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opa
  namespace: opa
  labels:
    app.kubernetes.io/instance: opa
    app.kubernetes.io/name: opa
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  rules:
    - host: changeme
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: opa
                port:
                  name: http