apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: prometheus
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
spec:
  resources:
    requests:
      storage: 20G
  accessModes:
    - ReadWriteMany
  volumeMode: Block